### ISSUE TITLE
deb: Address lintian errors

### ISSUE THREAD

**Issue by ashie** [clear-code/td-agent-builder#10]
Currently we get following lintian errors & warnings:

```
E: td-agent changes: bad-distribution-in-changes-file unstable
E: td-agent: embedded-library opt/td-agent/lib/ruby/2.4.0/x86_64-linux/psych.so: libyaml
E: td-agent: extended-description-is-empty
E: td-agent: no-copyright-file
W: td-agent: binary-without-manpage usr/bin/td
W: td-agent: binary-without-manpage usr/sbin/td-agent
W: td-agent: binary-without-manpage usr/sbin/td-agent-gem
W: td-agent: maintainer-script-needs-depends-on-adduser postinst
W: td-agent: maintainer-script-should-not-use-recursive-chown-or-chmod postinst:60
W: td-agent: maintainer-script-should-not-use-recursive-chown-or-chmod postinst:63
W: td-agent source: missing-debian-source-format
W: td-agent source: no-debian-copyright
W: td-agent: package-has-unnecessary-activation-of-ldconfig-trigger
W: td-agent: possibly-insecure-handling-of-tmp-files-in-maintainer-script postinst:62
W: td-agent source: unused-build-dependency-on-cdbs
W: td-agent: unusual-interpreter opt/td-agent/lib/ruby/gems/2.4.0/gems/bundler-1.16.6/lib/bundler/templates/Executable #!<%=
W: td-agent: unusual-interpreter opt/td-agent/lib/ruby/gems/2.4.0/gems/bundler-1.16.6/lib/bundler/templates/Executable.bundler #!<%=
W: td-agent: unusual-interpreter opt/td-agent/lib/ruby/gems/2.4.0/gems/bundler-1.16.6/lib/bundler/templates/Executable.standalone #!<%=
W: td-agent: uses-dpkg-database-directly postinst (line 37)
W: td-agent: uses-dpkg-database-directly postinst (line 40)
N: 360 tags overridden (224 errors, 136 warnings)
```

In addition, we are now suppressing more errors/warning by overriding lintian tags:

```
$ cat td-agent/debian/td-agent.lintian-overrides
td-agent: package-contains-vcs-control-file
td-agent: windows-devel-file-in-package
td-agent: dir-or-file-in-build-tree
td-agent: ruby-script-but-no-ruby-dep
td-agent: script-not-executable
td-agent: python-script-but-no-python-dep
td-agent: executable-not-elf-or-script
td-agent: missing-dep-for-interpreter
td-agent: gz-file-not-gzip
td-agent: no-upstream-changelog
td-agent: library-not-linked-against-libc
td-agent: wrong-path-for-interpreter
td-agent: duplicate-font-file
td-agent: jar-not-in-usr-share
td-agent: incorrect-libdir-in-la-file
```

We should ensure to address them by proper ways.

**Comment by kenhys** [comment]
> W: td-agent source: missing-debian-source-format

It is regarded to be as a native package.

**Comment by kenhys** [comment]
> > W: td-agent source: missing-debian-source-format
> 
> It is regarded to be as a native package.

I've created PR for this issue. https://github.com/clear-code/td-agent-builder/pull/39

**Comment by kenhys** [comment]
> E: td-agent: extended-description-is-empty

It seems that there is abstruction about td-agent, but not additional explanation.

**Comment by kenhys** [comment]
> > E: td-agent: extended-description-is-empty
> 
> It seems that there is abstruction about td-agent, but not additional explanation.

Ive created PR for this issue. https://github.com/clear-code/td-agent-builder/pull/40

**Comment by kenhys** [comment]
> E: td-agent changes: bad-distribution-in-changes-file unstable

It seems that changelog `td-agent (3.7.1-1) unstable; urgency=low` is wrong.

**Comment by kenhys** [comment]
./lib/apt/build.sh should be modified instead of td-agent/apt/build.sh.

**Comment by ashie** [comment]
> ./lib/apt/build.sh should be modified instead of td-agent/apt/build.sh.

Yes, later one is just copied from former one.

**Comment by kenhys** [comment]
> E: td-agent changes: bad-distribution-in-changes-file unstable

I've create PR for this issue https://github.com/clear-code/td-agent-builder/pull/41

**Comment by kenhys** [comment]
I've found trivial one in d/control, so I've also filed as PR about Homepage:
https://github.com/clear-code/td-agent-builder/pull/42

**Comment by kenhys** [comment]
> W: td-agent source: unused-build-dependency-on-cdbs

I've created PR for this issue. https://github.com/clear-code/td-agent-builder/pull/43

**Comment by kenhys** [comment]
Issue status is a bit moving forwarded.

* [ ] E: td-agent changes: bad-distribution-in-changes-file unstable https://github.com/clear-code/td-agent-builder/pull/41 woking
* [x] E: td-agent: extended-description-is-empty https://github.com/clear-code/td-agent-builder/pull/40
* [x] W: td-agent source: missing-debian-source-format https://github.com/clear-code/td-agent-builder/pull/39
* [ ] W: td-agent source: unused-build-dependency-on-cdbs https://github.com/clear-code/td-agent-builder/pull/43 (working)
* [x] Fixed Homepage: https://github.com/clear-code/td-agent-builder/pull/42

**Comment by kenhys** [comment]
A bit updated lintian on buster. some errors was fixed.

```
W: td-agent source: unused-build-dependency-on-cdbs
W: td-agent source: changelog-should-mention-nmu
W: td-agent source: source-nmu-has-incorrect-version-number 3.7.1-1
W: td-agent source: no-debian-copyright
W: td-agent-dbgsym: debug-file-with-no-debug-symbols usr/lib/debug/.build-id/6f/81198e00dfa50d5c65d06de9c3c04dcbb7d1ea.debug
W: td-agent-dbgsym: debug-file-with-no-debug-symbols usr/lib/debug/.build-id/a6/f706fb69f35b460a6374692c1fedd9d8d0bff3.debug
E: td-agent: no-copyright-file
W: td-agent: uses-dpkg-database-directly postinst (line 37)
W: td-agent: uses-dpkg-database-directly postinst (line 40)
W: td-agent: binary-without-manpage usr/bin/td
W: td-agent: binary-without-manpage usr/sbin/td-agent
W: td-agent: binary-without-manpage usr/sbin/td-agent-gem
W: td-agent: incorrect-path-for-interpreter opt/td-agent/bin/jeprof (#!/usr/bin/env perl != /usr/bin/perl)
W: td-agent: unusual-interpreter opt/td-agent/lib/ruby/gems/2.4.0/gems/bundler-1.16.6/lib/bundler/templates/Executable #!<%=
W: td-agent: unusual-interpreter opt/td-agent/lib/ruby/gems/2.4.0/gems/bundler-1.16.6/lib/bundler/templates/Executable.bundler #!<%=
W: td-agent: unusual-interpreter opt/td-agent/lib/ruby/gems/2.4.0/gems/bundler-1.16.6/lib/bundler/templates/Executable.standalone #!<%=
W: td-agent: maintainer-script-should-not-use-recursive-chown-or-chmod postinst:60
W: td-agent: possibly-insecure-handling-of-tmp-files-in-maintainer-script postinst:62
W: td-agent: maintainer-script-should-not-use-recursive-chown-or-chmod postinst:63
W: td-agent: package-has-unnecessary-activation-of-ldconfig-trigger
N: 278 tags overridden (151 errors, 127 warnings); 1 unused override
N: Some overrides were ignored, since the tags were marked "non-overridable".
N: Use --verbose for more information.
```

**Comment by kenhys** [comment]
I'm working on manpage.

**Comment by kenhys** [comment]
I've fixed https://github.com/clear-code/td-agent-builder/pull/45

```
W: td-agent: binary-without-manpage usr/bin/td
W: td-agent: binary-without-manpage usr/sbin/td-agent
W: td-agent: binary-without-manpage usr/sbin/td-agent-gem
```

**Comment by kenhys** [comment]
Related to #45, I've found a typo in td-agent-gem, I'll feedback to upstream

**Comment by kenhys** [comment]
> Related to #45, I've found a typo in td-agent-gem, I'll feedback to upstream
https://github.com/ruby/ruby/blob/ac2c07e98373bb62be618001c897fa9d5809d8a4/lib/rubygems/command.rb#L651

 Already fixed in upstream.

**Comment by kenhys** [comment]
I've fixed  W: td-agent: unusual-interpreter via  https://github.com/clear-code/td-agent-builder/pull/46

**Comment by kenhys** [comment]
> W: td-agent: possibly-insecure-handling-of-tmp-files-in-maintainer-script postinst:62

Fixed in  https://github.com/clear-code/td-agent-builder/pull/47

**Comment by kenhys** [comment]
Progress summary:

* W:binary-without-manpage https://github.com/clear-code/td-agent-builder/pull/45 (on review)
* W:unusual-interpreter https://github.com/clear-code/td-agent-builder/pull/46 (on review)
* W:possibly-insecure-handling-of-tmp-files-in-maintainer-script https://github.com/clear-code/td-agent-builder/pull/47 (review feedback fixed)
* W:maintainer-script-should-not-use-recursive-chown-or-chmod https://github.com/clear-code/td-agent-builder/pull/48 (waiting review)
* W:package-has-unnecessary-activation-of-ldconfig-trigger https://github.com/clear-code/td-agent-builder/pull/49 (wating review)

**Comment by kenhys** [comment]
Here is the progress, 

* W:binary-without-manpage
　* https://github.com/clear-code/td-agent-builder/pull/45 (Fixed CI)
* W:unusual-interpreter
  * https://github.com/clear-code/td-agent-builder/pull/46 (Tried to simplify by wildcard, but not succeeded)
* W:maintainer-script-should-not-use-recursive-chown-or-chmo
  * https://github.com/clear-code/td-agent-builder/pull/48 (Fixed and merged)

**Comment by kenhys** [comment]
I'll fix E: td-agent: no-copyright-file

**Comment by kenhys** [comment]
Progress summary:

* W:binary-without-manpage deb: install missing manpages 
  * https://github.com/clear-code/td-agent-builder/pull/45 (Merged)
* W: incorrect-path-for-interpreter
  * https://github.com/clear-code/td-agent-builder/pull/55 (Merged)
* E: td-agent: no-copyright-file
  * https://github.com/clear-code/td-agent-builder/pull/56 (Work in progress)

**Comment by kenhys** [comment]
Current status of lintian with master: 

```
W: td-agent source: changelog-should-mention-nmu
W: td-agent source: source-nmu-has-incorrect-version-number 3.7.1-1
W: td-agent source: no-debian-copyright
E: td-agent: no-copyright-file
W: td-agent: uses-dpkg-database-directly postinst (line 37)
W: td-agent: uses-dpkg-database-directly postinst (line 40)
W: td-agent-dbgsym: debug-file-with-no-debug-symbols usr/lib/debug/.build-id/6f/81198e00dfa50d5c65d06de9c3c04dcbb7d1ea.debug
W: td-agent-dbgsym: debug-file-with-no-debug-symbols usr/lib/debug/.build-id/a6/f706fb69f35b460a6374692c1fedd9d8d0bff3.debug
N: 222 tags overridden (106 errors, 116 warnings); 2 unused overrides
N: Some overrides were ignored, since the tags were marked "non-overridable".
N: Use --verbose for more information.
```
 I'm working on E:td-agent: co-copyright-file in https://github.com/clear-code/td-agent-builder/pull/56

**Comment by kenhys** [comment]
It seems that it is better to inject  new depended rake task to build:deb_config

**Comment by kenhys** [comment]
missing license by gem specificaiton:

```
cool.io-1.6.0.gem
async-pool-0.2.0.gem
td-0.16.8.gem
webhdfs-0.9.0.gem
```

**Comment by kenhys** [comment]
I've send PR to add missing licenses.

https://github.com/tarcieri/cool.io/pull/67
https://github.com/socketry/async-pool/pull/4
https://github.com/treasure-data/td/pull/236
https://github.com/kzk/webhdfs/pull/38

**Comment by kenhys** [comment]
I've fixed #56

**Comment by kenhys** [comment]
https://github.com/tarcieri/cool.io/pull/67 merged
https://github.com/socketry/async-pool/pull/4 merged
https://github.com/kzk/webhdfs/pull/38 merged

**Comment by kenhys** [comment]
TODO:

* W: td-agent source: space-in-std-shortname-in-dep5-copyright
* E: td-agent: incorrect-libdir-in-la-file
* W: td-agent: package-contains-vcs-control-file
* W: td-agent-dbgsym(may be overrided)

**Comment by kenhys** [comment]
```
W: td-agent source: missing-license-paragraph-in-dep5-copyright apache license version 2.0 (paragraph at line 128)
W: td-agent source: space-in-std-shortname-in-dep5-copyright apache license version 2.0 (paragraph at line 128)
```

It is better to feedback to ruby-kafka about gemspec license field. http://spdx.org/licenses/

```
Files: downloads/plugin_gems/15-ruby-kafka-1.0.0.gem
Copyright: Daniel Schierbeck
License: Apache License Version 2.0
```

**Comment by kenhys** [comment]
I've fixed spdx license warning.
https://github.com/clear-code/td-agent-builder/pull/57

**Comment by kenhys** [comment]
I've fixed E: td-agent: incorrect-libdir-in-la-file
https://github.com/clear-code/td-agent-builder/pull/58

**Comment by kenhys** [comment]
I've fixed W: td-agent: package-contains-vcs-control-file
https://github.com/clear-code/td-agent-builder/pull/59

**Comment by kenhys** [comment]
I've send another PR to remove unused override rule.
https://github.com/clear-code/td-agent-builder/pull/60

**Comment by kenhys** [comment]
close this issue if https://github.com/clear-code/td-agent-builder/pull/63 is merged.

**Comment by kenhys** [comment]
As all PRs are merged, I'll close this PR!
