### ISSUE TITLE
Support Amazon Linux 2

### ISSUE THREAD

**Issue by repeatedly** [clear-code/td-agent-builder#72]
AWS provides Amazon Linux 2 images for amd64/arm64v8: https://hub.docker.com/_/amazonlinux

The problem is Amazon Linux 2 is similar to CentOS 7 but not the same.

- Need to use `amazon-linux-extras` to install ruby 2.4/2.6. No `centos-release-scl`.
- No `/etc/redhat-release`.  Maybe, fixed distribution/distribution_version is enough
- Need to update td-agent.spec.in for amazon linux 2
- May hit other difference point...

**Comment by ashie** [comment]
I'll check it.

**Comment by ashie** [comment]
Done in #74

>     * May hit other difference point...

I'll file a new issue if I find other differences.

**Comment by repeatedly** [comment]
Awesome! I have just confirmed building rpm is succeeded :)
