### ISSUE TITLE
rpm: check regression in  maintainer script 

### ISSUE THREAD

**Issue by kenhys** [clear-code/td-agent-builder#82]
# Problem

https://github.com/treasure-data/omnibus-td-agent/tree/master/templates/package-scripts/td-agent/rpm
was removed, but there may be a possibility that it is not migrated properly.

**Comment by kenhys** [comment]
https://github.com/treasure-data/omnibus-td-agent/blob/master/templates/package-scripts/td-agent/rpm/postun
is ok because it is just empty.

**Comment by kenhys** [comment]
https://github.com/treasure-data/omnibus-td-agent/blob/master/templates/package-scripts/td-agent/rpm/preun
functionality seems missing in spec. need to port  `%preun`.

**Comment by ashie** [comment]
> # Problem
> 
> https://github.com/treasure-data/omnibus-td-agent/tree/master/templates/package-scripts/td-agent/rpm
> was removed, but there may be a possibility that it is not migrated properly.

#80 is one of such case.

**Comment by kenhys** [comment]
https://github.com/treasure-data/omnibus-td-agent/blob/master/templates/package-scripts/td-agent/rpm/post#L24

/etc/td-agent/plugin directory seems missing in spec.

**Comment by kenhys** [comment]
https://github.com/treasure-data/omnibus-td-agent/blob/master/templates/package-scripts/td-agent/rpm/post#L33

prelink support seems missing in spec.

**Comment by kenhys** [comment]
https://github.com/treasure-data/omnibus-td-agent/blob/master/templates/package-scripts/td-agent/rpm/post#L54

/var/log/td-agent/buffer seems missing in spec.

**Comment by kenhys** [comment]
https://github.com/treasure-data/omnibus-td-agent/blob/master/templates/package-scripts/td-agent/rpm/post#L101

restart on upgrade seems missing in spec.

**Comment by kenhys** [comment]
I'll fix https://github.com/clear-code/td-agent-builder/issues/82#issuecomment-637952044 via 

https://github.com/clear-code/td-agent-builder/pull/83

**Comment by kenhys** [comment]
TODO:

* %preun https://github.com/clear-code/td-agent-builder/pull/83
* /etc/td-agent/plugin
* prelink support
* /var/log/td-agent/buffer/
* restart on upgrade

**Comment by kenhys** [comment]
> /etc/td-agent/plugin
> /var/log/td-agent/buffer/

I've fixed via https://github.com/clear-code/td-agent-builder/pull/87

**Comment by kenhys** [comment]
%preun and restart issue is fixed via https://github.com/clear-code/td-agent-builder/pull/83

**Comment by kenhys** [comment]
about /tmp/td-agent , working on https://github.com/clear-code/td-agent-builder/pull/88

**Comment by kenhys** [comment]
about prelink, working on https://github.com/clear-code/td-agent-builder/pull/89

**Comment by kenhys** [comment]
about /tmp/td-agent, I've fixed PR　https://github.com/clear-code/td-agent-builder/pull/88

**Comment by kenhys** [comment]
I've fixed #89

**Comment by kenhys** [comment]
When #89 was merged, we can close this issue.

**Comment by cosmo0920** [comment]
Let's close this ticket! :muscle:
When another regression or issue is found, we should open an another ticket.
