### ISSUE TITLE
ubuntu-bionic-arm64 build failed with "175 errors, 61 warnings"

### ISSUE THREAD

**Issue by Xphobia** [clear-code/td-agent-builder#96]
# Problem
Build "ubuntu-bionic-arm64" target failed, with logs "175 errors, 61 warnings" at last.
I aslo checked td-agent/apt/repositories/ directory, it's empty.
The builder (container) is still running at last.

# Build environment
my vps host is ubuntu bionic on x86_64 platform, 1CPU and 1 GB RAM.

# How to reproduce
Follow the instructions in Readme to build
```
export TARGET_BASE="ubuntu-bionic"
sudo apt install qemu-user-static
cd /path/to/td-agent-builder
cp /usr/bin/qemu-aarch64-static td-agent/apt/${TARGET_BASE}
rake apt:build APT_TARGETS="${TARGET_BASE}-arm64"
```

# Expected
Build successfully

# Actual
Build failed

# Builder logs
I check the builder logs using "docker logs -f  860a5cd80e74" and find there are some ruby extensions failed.
![C)K9B@3V5J`TSL_6LYPIF](https://user-images.githubusercontent.com/59901623/84333400-3d611880-abc2-11ea-80e4-12563736484a.png)
![ACCQ4ZVHAX)UHQBM 34H)}8](https://user-images.githubusercontent.com/59901623/84333415-481bad80-abc2-11ea-8bb8-5c4a028b8438.png)
At last, it failed with "175 errors, 61 warnings" 
![WYA4)U N{~1XRIN_K4}Z4IK](https://user-images.githubusercontent.com/59901623/84333462-6b465d00-abc2-11ea-9ad1-5b8dbef36800.png)
This is the log file dumped by "docker logs  860a5cd80e74 > td-agent-builder.log "
[td-agent-builder.log](https://github.com/clear-code/td-agent-builder/files/4761997/td-agent-builder.log)

**Comment by ashie** [comment]
> Build "ubuntu-bionic-arm64" target failed, with logs "175 errors, 61 warnings" at last.

These warnings and errors are reported by a package checking tool (lintian), building the package itself is succeeded . Most of warnings or errors of lintian is false-positive or ignorable. Same warning or errors are reported also on my environment which can build the package correctly.

> This is the log file dumped by "docker logs 860a5cd80e74 > td-agent-builder.log "
td-agent-builder.log

It seems that building the package is finished by not yet copied to the host.

Here is the tail of my log on finishing successfuly to build the package.

```
N: 236 tags overridden (175 errors, 61 warnings)
Finished running lintian.
/build
cd -
cd -
```

> my vps host is ubuntu bionic on x86_64 platform, 1CPU and 1 GB RAM.

The memory amount might not be enough.

**Comment by Xphobia** [comment]
> The memory amount might not be enough.
Thanks, that may be the case. The instance's configuration is too low and take much time to build. I will upgrade it later and try to build again.

And another question: can i costomize gem plugins into td-agent using the builder.
Acctually, i'm compiling a fluentd container image from kolla project on platform ububtu/arm64. I checked the fluentd's Dockerfile , it needs more gem plugins. and i want to bundler these into td-agent to. How can i do it ?

**Comment by ashie** [comment]
> And another question: can i customize gem plugins for td-agent using the builder?
> Acctually, i'm compiling a fluentd container image from kolla project on platform ubuntu/arm64. I checked the fluentd's Dockerfile , it needs more gem plugins. and i want to bundle these into td-agent . How can i do it ?

See https://github.com/clear-code/td-agent-builder#how-to-bump-up-the-package-version

1. Edit td-agent/plugin_gems.rb
2. Commit it by `git commit -a`
3. Rebuild the package

**Comment by ashie** [comment]
If you can't build it even if you increase amount of memory, please reopen this issue.

**Comment by Xphobia** [comment]
I upgrade the instance with 2 CPU and 4GB RAM and rebuild td-agent. There seems nothing improved except the time cost. The log is still same as before.
```
N: 236 tags overridden (175 errors, 61 warnings)
Finished running lintian.
```
That is a bit different from yours. There is no 
```
/build
cd -
cd -
```

> It seems that building the package is finished but not yet copied to the host.

I log into the builder (container), and  "td-agent_3.7.1-1_arm64.deb" is in /build directory. Is the package size (9.8M) ok ? If it's ok, i can copy it to host by "docker cp".
![%T P65}HGID( VKCZ`K%}8](https://user-images.githubusercontent.com/59901623/84455291-8af78700-ac8f-11ea-9340-057a384bea24.png)

**Comment by ashie** [comment]
> Is the package size (9.8M) ok ?

OK, it's expected size range.
